//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotMailer.CreateAccount.AccountsApiServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiAccount", Namespace="http://apiconnector.com")]
    [System.SerializableAttribute()]
    public partial class ApiAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        private dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccountProperty[] PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccountProperty[] Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiAccountProperty", Namespace="http://apiconnector.com")]
    [System.SerializableAttribute()]
    public partial class ApiAccountProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiUser", Namespace="http://apiconnector.com")]
    [System.SerializableAttribute()]
    public partial class ApiUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiManagedUser", Namespace="http://apiconnector.com")]
    [System.SerializableAttribute()]
    public partial class ApiManagedUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string PasswordField;
        
        private dotMailer.CreateAccount.AccountsApiServiceReference.ApiPermissionTypes[] PermissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public dotMailer.CreateAccount.AccountsApiServiceReference.ApiPermissionTypes[] Permissions {
            get {
                return this.PermissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PermissionsField, value) != true)) {
                    this.PermissionsField = value;
                    this.RaisePropertyChanged("Permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiPermissionTypes", Namespace="http://apiconnector.com")]
    public enum ApiPermissionTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAvailableInThisVersion = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactExporter = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contacts = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EditCampaigns = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Programs = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reporter = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportDrillDown = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sender = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateAdmin = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViewAccountInvoices = 70,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiOAuthToken", Namespace="http://apiconnector.com")]
    [System.SerializableAttribute()]
    public partial class ApiOAuthToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RedirectUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RedirectUri {
            get {
                return this.RedirectUriField;
            }
            set {
                if ((object.ReferenceEquals(this.RedirectUriField, value) != true)) {
                    this.RedirectUriField = value;
                    this.RaisePropertyChanged("RedirectUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string SecretKey {
            get {
                return this.SecretKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretKeyField, value) != true)) {
                    this.SecretKeyField = value;
                    this.RaisePropertyChanged("SecretKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiTheme", Namespace="http://apiconnector.com")]
    [System.SerializableAttribute()]
    public partial class ApiTheme : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PrimaryColorField;
        
        private string SecondaryColorField;
        
        private string HyperlinkColorField;
        
        private string ButtonColorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PrimaryColor {
            get {
                return this.PrimaryColorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryColorField, value) != true)) {
                    this.PrimaryColorField = value;
                    this.RaisePropertyChanged("PrimaryColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SecondaryColor {
            get {
                return this.SecondaryColorField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryColorField, value) != true)) {
                    this.SecondaryColorField = value;
                    this.RaisePropertyChanged("SecondaryColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string HyperlinkColor {
            get {
                return this.HyperlinkColorField;
            }
            set {
                if ((object.ReferenceEquals(this.HyperlinkColorField, value) != true)) {
                    this.HyperlinkColorField = value;
                    this.RaisePropertyChanged("HyperlinkColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string ButtonColor {
            get {
                return this.ButtonColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ButtonColorField, value) != true)) {
                    this.ButtonColorField = value;
                    this.RaisePropertyChanged("ButtonColor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://apiconnector.com/v2", ConfigurationName="AccountsApiServiceReference.AccountsApiService")]
    public interface AccountsApiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateAccount", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateAccountResponse")]
        dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount CreateAccount(dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount apiAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateAccount", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateAccountResponse")]
        System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount> CreateAccountAsync(dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount apiAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateApiUser", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateApiUserResponse")]
        dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser CreateApiUser(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser apiUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateApiUser", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateApiUserResponse")]
        System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser> CreateApiUserAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser apiUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateManagedUser", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateManagedUserResponse")]
        dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser CreateManagedUser(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser apiManagedUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateManagedUser", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateManagedUserResponse")]
        System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser> CreateManagedUserAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser apiManagedUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateOAuthToken", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateOAuthTokenResponse")]
        dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken CreateOAuthToken(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken apiOAuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/CreateOAuthToken", ReplyAction="http://apiconnector.com/v2/AccountsApiService/CreateOAuthTokenResponse")]
        System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken> CreateOAuthTokenAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken apiOAuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/UpdateTheme", ReplyAction="http://apiconnector.com/v2/AccountsApiService/UpdateThemeResponse")]
        void UpdateTheme(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiTheme apiTheme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apiconnector.com/v2/AccountsApiService/UpdateTheme", ReplyAction="http://apiconnector.com/v2/AccountsApiService/UpdateThemeResponse")]
        System.Threading.Tasks.Task UpdateThemeAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiTheme apiTheme);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountsApiServiceChannel : dotMailer.CreateAccount.AccountsApiServiceReference.AccountsApiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountsApiServiceClient : System.ServiceModel.ClientBase<dotMailer.CreateAccount.AccountsApiServiceReference.AccountsApiService>, dotMailer.CreateAccount.AccountsApiServiceReference.AccountsApiService {
        
        public AccountsApiServiceClient() {
        }
        
        public AccountsApiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountsApiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsApiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount CreateAccount(dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount apiAccount) {
            return base.Channel.CreateAccount(apiAccount);
        }
        
        public System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount> CreateAccountAsync(dotMailer.CreateAccount.AccountsApiServiceReference.ApiAccount apiAccount) {
            return base.Channel.CreateAccountAsync(apiAccount);
        }
        
        public dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser CreateApiUser(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser apiUser) {
            return base.Channel.CreateApiUser(accountId, apiUser);
        }
        
        public System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser> CreateApiUserAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiUser apiUser) {
            return base.Channel.CreateApiUserAsync(accountId, apiUser);
        }
        
        public dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser CreateManagedUser(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser apiManagedUser) {
            return base.Channel.CreateManagedUser(accountId, apiManagedUser);
        }
        
        public System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser> CreateManagedUserAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiManagedUser apiManagedUser) {
            return base.Channel.CreateManagedUserAsync(accountId, apiManagedUser);
        }
        
        public dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken CreateOAuthToken(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken apiOAuthToken) {
            return base.Channel.CreateOAuthToken(accountId, apiOAuthToken);
        }
        
        public System.Threading.Tasks.Task<dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken> CreateOAuthTokenAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiOAuthToken apiOAuthToken) {
            return base.Channel.CreateOAuthTokenAsync(accountId, apiOAuthToken);
        }
        
        public void UpdateTheme(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiTheme apiTheme) {
            base.Channel.UpdateTheme(accountId, apiTheme);
        }
        
        public System.Threading.Tasks.Task UpdateThemeAsync(int accountId, dotMailer.CreateAccount.AccountsApiServiceReference.ApiTheme apiTheme) {
            return base.Channel.UpdateThemeAsync(accountId, apiTheme);
        }
    }
}
